### ISSUE TITLE
port 445 timeout even with firewall tcp port opened

### ISSUE THREAD

**Issue by giuliohome** [Azure-Samples/azure-files-samples#102]
I'm testing 

`sudo mount --verbose  -t cifs //logvolume.file.core.windows.net/aksshare /mnt/aksshare -o vers=3.0,credentials=/etc/smbcredentials/logvolume.cred,dir_mode=0777,file_mode=0777,serverino`

which fails with

```
me.cred,dir_mode=0777,file_mode=0777,serverino
mount.cifs kernel mount options: ip=20.150.95.8,unc=\\logvolume.file.core.windows.net\aksshare,vers=3.0,dir_mode=0777,file_mode=0777,serverino,user=logvolume,pass=********
mount error(115): Operation now in progress
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
```

and log messages

```
[ 6317.931829] CIFS: Attempting to mount \\logvolume.file.core.windows.net\aksshare
[ 6328.381224] CIFS: VFS: Error connecting to socket. Aborting operation.
[ 6328.381247] CIFS: VFS: cifs_mount failed w/return code = -115
```

I've installed and used this tool

`sudo bash AzFileDiagnostics.sh -u //logvolume.file.core.windows.net/aksshare`

and the problem is still

```
2022-04-30T09:18:18.768Z Checking: Check if client has any connectivity issue with storage account
2022-04-30T09:18:18.770Z Storage account FQDN is logvolume.file.core.windows.net
2022-04-30T09:18:18.772Z Getting the Iptables policies
2022-04-30T09:18:18.830Z Test the storage account IP connectivity over TCP port 445
2022-04-30T09:18:29.200Z Error: Port 445 is not reachable from this client and the error is Connection Timeout or Error happens
```

Looking at the source code here I see that it does

`nc -v -z -w 5 logvolume.file.core.windows.net  445`

and it gets a timeout

```
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: TIMEOUT.
```

Are the credentials not yet requested in this phase of connection?
Anyway I stored them and used in the mount command, according to azure connect button's output.
Is it due to the firewall?
I've opened the tcp port in the firewall
```
firewall-cmd --list-ports
445/tcp 1025-65535/tcp 1025-65535/udp
```
 
I've asked the [question](https://docs.microsoft.com/en-us/answers/questions/832405/can39t-mount-file-share-tcp-port-445.html) on Microsoft Azure Q&A about storage accounts.

Can you help me with this or point me to next action I have to do?
Thanks

**Comment by Mike-Crowley** [comment]
I realize this is an old post, but in many cases 445 is blocked by the ISP. 

See "Cause 1" here:
https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/files-troubleshoot-smb-connectivity?tabs=windows#cause-1-port-445-is-blocked

Which mentions this community TechNet page which lists some of the problematic ISPs:

https://social.technet.microsoft.com/wiki/contents/articles/32346.azure-summary-of-isps-that-allow-disallow-access-from-port-445.aspx

FWIW, I'm also troubleshooting 445 connectivity to a Private Link over a VPN and the above doesn't help me, but I figured I'd mention this for anyone else finding your post.

**Comment by giuliohome** [comment]
@Mike-Crowley Are you confirming that there is no solution if port 445 is blocked by the ISP?

**Comment by Mike-Crowley** [comment]
See the first link I posted. There are 4 solutions mentioned, such as using a VPN.

**Comment by giuliohome** [comment]
Yes, I've seen them, but in my opinion, those are not really "solutions" for the standard SMB mount. Instead, I would view them as different alternatives. Thanks anyway.

**Comment by Mike-Crowley** [comment]
No disagreement from me. But the "solution" to your ISP blocking a port is only "solved" by having them not do that. :)

**Comment by giuliohome** [comment]
I'm not entirely certain whether the ISP is blocking the port. On the other hand, I'm curious about how the service can be provided in countries where that port is effectively blocked by every ISP. I perceive a communication challenge/problem in terms of clarifying these aspects. One possible underlying reason for these issues might be that SMB mounts are now generally considered unsafe by security teams.

**Comment by Mike-Crowley** [comment]
Yep, even Microsoft has support for people who perceive it as part of defense in depth: https://support.microsoft.com/en-us/topic/preventing-smb-traffic-from-lateral-connections-and-entering-or-leaving-the-network-c0541db7-2244-0dce-18fd-14a3ddeb282a
