### ISSUE TITLE
EnableActiveDirectoryDomainServicesForFile is hardcoded

### ISSUE THREAD

**Issue by JohnLBevan** [Azure-Samples/azure-files-samples#11]
Currently the parameter `EnableActiveDirectoryDomainServicesForFile` for cmdlet `Set-AzStorageAccount` is hardcoded to `$true`; [related line](https://github.com/Azure-Samples/azure-files-samples/blob/44164ffa11cf387f225ce82b840e9abae622a74f/AzFilesHybrid/AzFilesHybrid.psm1#L2730).

Since some users may have set this property already it would be good if the routine either checked this first and set the flag only if required, or presented this parameter on the calling function.

**Comment by YunZhou-MS** [comment]
Hi John,

In our latest release [v0.1.3,](https://github.com/Azure-Samples/azure-files-samples/releases/tag/v0.1.3), the cmdlet is updated to have two additional options to control the behaviors. Option "-DisableADDS" lets you to set EnableActiveDirectoryDomainServicesForFile to $false. Option "-Force" lets you to choose whether to report the existence or overwrite if the property already exists. Hope this help. Please let us know if you have any questions.

Best regards,
Yun
