### ISSUE TITLE
`Update-AzStorageAccountADObjectPassword`: `$otherKerbKey` may be null

### ISSUE THREAD

**Issue by JohnLBevan** [Azure-Samples/azure-files-samples#12]
Should someone run `Update-AzStorageAccountADObjectPassword` against an incorrectly setup storage account (i.e. one partially created manually ahead of using these cmdlets) it's possible that there is no second key; thus `$otherKerbKey` will have a value of `$null` and will throw an exception on the following line: 

https://github.com/Azure-Samples/azure-files-samples/blob/44164ffa11cf387f225ce82b840e9abae622a74f/AzFilesHybrid/AzFilesHybrid.psm1#L3016

This line appears to now be redundant anyway (i.e. the `else` block where it had been used is now commented out), so it should be safe to remove the above line/avoiding such issues.

**Comment by YunZhou-MS** [comment]
Hi John,

Thank you for your comment! We have fixed this issue in our latest release [v0.1.3](https://github.com/Azure-Samples/azure-files-samples/releases/tag/v0.1.3).

Best regards,
Yun
