### ISSUE TITLE
If AZ.Storage module not installed Import-AZHybridFiles fails

### ISSUE THREAD

**Issue by emmclare** [Azure-Samples/azure-files-samples#14]
$storageModule = Get-Module -Name Az.Storage -ListAvailable | `
        Where-Object { 
            $_.Version -eq [Version]::new(1,8,2) -or 
            $_.Version -eq [Version]::new(1,11,1) 
        } | `
        Sort-Object -Property Version -Descending

...

            if ($null -eq $storageModule) {
                Remove-Module `
                        -Name Az.Storage `
                        -Force `
                        -ErrorAction SilentlyContinue
                
                try {
                    Uninstall-Module `
                            -Name Az.Storage `
                            -Force `
                            -ErrorAction Stop
                } catch {
                    Write-Error `
                            -Message "Unable to uninstall the GA version of the Az.Storage module in favor of the preview version (1.11.1-preview)." `
                            -ErrorAction Stop
                }

The above assumes that there is an invalid version of AZ.Storage installed.  If AZ.Storage is not installed at all, we fail the uninstall and exit.  Needs to handle case where no AZ.Storage module is present at all.

**Comment by YunZhou-MS** [comment]
Hi Emily,

Thank you for your comment! This issue is fixed in our latest release [v0.1.3](https://github.com/Azure-Samples/azure-files-samples/releases/tag/v0.1.3). Please let us know if you have any questions.

Best regards,
Yun
