### ISSUE TITLE
code not signed

### ISSUE THREAD

**Issue by efd7887** [Azure-Samples/azure-files-samples#196]
We implement strict code signing and we cannot use this module (and need to) due to our policy.  The code needs to be signed.  We cannot circumvent our security policy by changing the execution policy.  
![img](https://github.com/Azure-Samples/azure-files-samples/assets/32522641/cd91548f-38c7-4eb6-b026-e41477c71005)

**Comment by MaximeKjaer** [comment]
The latest releases are now signed. Closing this bug as fixed, but please re-open if you have any further issues with the code signing.
