### ISSUE TITLE
Error during execution of Join-AzStorageAccountForAuth cmdlet.

### ISSUE THREAD

**Issue by rinaldochristy** [Azure-Samples/azure-files-samples#21]
I am unable to successfully execute the cmdlet Join-AzStorageAccountForAuth.

I receive the below error message:

Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0954
At C:\Users\Viaguladas\Documents\WindowsPowerShell\Modules\AzFilesHybrid\0.1.2.0\AzFilesHybrid.psm1:503 char:33
+                                 Add-WindowsCapability -Online | `
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
 
Import-Module : The specified module 'ActiveDirectory' was not loaded because no valid module file was found in any module directory.
At C:\Users\Viaguladas\Documents\WindowsPowerShell\Modules\AzFilesHybrid\0.1.2.0\AzFilesHybrid.psm1:760 char:9
+         Import-Module -Name ActiveDirectory
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ActiveDirectory:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0954
At C:\Users\Viaguladas\Documents\WindowsPowerShell\Modules\AzFilesHybrid\0.1.2.0\AzFilesHybrid.psm1:503 char:33
+                                 Add-WindowsCapability -Online | `
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand

**Comment by rinaldochristy** [comment]
Below is a screenshot of the error:

![image](https://user-images.githubusercontent.com/45920198/81987238-8d87a200-9639-11ea-9662-297f13a83978.png)

**Comment by KenKilty** [comment]
@rinaldochristy I had the same error. Be sure to run the scripts from a workstation that has the Remote Server Administration Tools (RSAT) installed. Once RSAT is installed the module will exist here C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ActiveDirectory and the Join-AzStorageAccountForAuth will complete.

**Comment by YunZhou-MS** [comment]
Hi @rinaldochristy,

On Windows client machine, this issue can happen if there is a local update service in your environment configured by group policy. There is a workaround described in [Windows 10 - 1809 - RSAT Toolset - error code of 0x800f0954](https://social.technet.microsoft.com/Forums/en-US/42bfdd6e-f191-4813-9142-5c86a2797c53/windows-10-1809-rsat-toolset-error-code-of-0x800f0954?forum=win10itprogeneral). Please check if it helps address your issue.

Thanks,
Yun

**Comment by rinaldochristy** [comment]
Issue resolved after downloading RSAT. Thanks Guys! Appreciate it!
