### ISSUE TITLE
AzFilesHybrid: Az module detection not working

### ISSUE THREAD

**Issue by KenKilty** [Azure-Samples/azure-files-samples#22]
The Az module detection log appears to be not working with Az modules > v2.x a message is logged:

`Install Azure PowerShell modules
This module requires Azure PowerShell ("Az" module) 2.8.0+ and Az.Storage 1.8.2-preview+. This can be installed now if
you are running as an administrator.`

In environments where I have the following installed:

Script     4.1.0      az
Script     2.0.0      Az.Storage

The error is non-blocking if you run the sample scripts piecemeal but it will block them if you attempt to run through in a single execution.

**Comment by YunZhou-MS** [comment]
Hi @KenKilty,

With the [latest release](https://github.com/Azure-Samples/azure-files-samples/releases/latest) of AzFilesHybrid module, we have upgraded to support Az.Storage module with a version equal to or greater than 2.0.0. Hope this help address your issue.

Best regards,
Yun
