### ISSUE TITLE
Unable to install, multiple modules matched 'Az.Storage'

### ISSUE THREAD

**Issue by NebV** [Azure-Samples/azure-files-samples#25]
Fix: added `-Repository "PSGallery"` under Install Module section for Az.Storage in "AzFilesHybrid.psm1"
Error getting:
`This module requires Azure PowerShell ("Az" module) 2.8.0+ and Az.Storage 1.8.2-preview+. This can be installed now if you are running as an administrator.
[Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "Yes"): A
WARNING: 'Az.Storage' matched module 'Az.Storage/1.11.1-preview' from provider: 'PowerShellGet', repository 'PSGallery'.
WARNING: 'Az.Storage' matched module 'Az.Storage/1.11.1-preview' from provider: 'PowerShellGet', repository 'PSGalleryInt'.
R : Unable to install, multiple modules matched 'Az.Storage'. Please specify a single -Repository.
At line:1 char:1
+ R
+ ~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Invoke-History], Exception
    + FullyQualifiedErrorId : DisambiguateForInstall,Microsoft.PowerShell.Commands.InvokeHistoryCommand`

**Comment by YunZhou-MS** [comment]
Hi @NebV,

This issue has been fixed in the [latest release](https://github.com/Azure-Samples/azure-files-samples/releases/latest) of AzFilesHybrid module, where 'PSGallery' is used. Hope this helps address your issue.

Best regards,
Yun
