### ISSUE TITLE
OU Path issue

### ISSUE THREAD

**Issue by ryansmyth2001** [Azure-Samples/azure-files-samples#26]
Hi All,

Wondering if anybody has come across the below issue? Seems to be looking for an OU called Associates? I am defo putting in the the right OU DN.

PS E:\Scripts\AzFilesHybrid> Join-AzStorageAccountForAuth `
                                             -ResourceGroupName $ResourceGroupName `
                                             -Name $StorageAccountName `
                                             -Domain "xxx" `
                                             -DomainAccountType "ComputerAccount" `
                                             -OrganizationalUnitDistinguishedName "xxx"
Get-ADOrganizationalUnit: Variable: 'OrganizationalUnit' found in expression: $OrganizationalUnit is not defined.
Write-Error: C:\Users\Documents\PowerShell\Modules\AzFilesHybrid\0.1.2.0\AzFilesHybrid.psm1:3836:37
Line |
3836 |  … eOverride = New-ADAccountForStorageAccount @newParams -ErrorAction St …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find an organizational unit with name 'Associates' in the xxxx domain

**Comment by ryansmyth2001** [comment]
Sorry ignore this one..got it resolved.. user error! :-)

**Comment by fabianops** [comment]
> Sorry ignore this one..got it resolved.. user error! :-)

I have the same error, what did you do to solve it?

**Comment by ryansmyth2001** [comment]
It was down to my OU name for some reason, not sure what the problem was as I copied and pasted the DN from AD..(maybe whitespace or something odd)
Anyway in the end think I switched to use the OrganizationalUnitName switch instead of OrganizationalUnitDistinguishedName and typed the OU name in then moved the switch from last in the command to first in the command and it worked.

My next issue is now getting cross forest working!

**Comment by fabianops** [comment]
thanks, I changed to OrganizationalUnitName and it worked too.
